### ISSUE TITLE
An error occurred during Reset buffer sizes

### ISSUE THREAD

**Issue by Zachary-Zuo** [jan-van-bergen/GPU-Pathtracer#22]
Your work is excellent, but I found that the program has been stuck in the global_buffer_sizes.set_value(*pinned_buffer_sizes); statement in the Pathtracer.cpp when I run it after compiling. Do you know what the problem is and how to solve it?

**Comment by Kuranes** [comment]
FYI never had the probleme on a 1070 nvidia, but changed gpu and got stuck as soon as I changed to 3060, cannot run it anymore now that I have this gpu.  
no cuda debug tools gives any info whatsover, it's deadlocked somewhere for sure.
If you want ot test you need to downgrade on a 1070 (or send author a 3060 :) )

That points to some deadlock on block/thread upon GPU capabailities, and require knowledge of where to poke to debug it

**Comment by jan-van-bergen** [comment]
Thanks for the feedback!
I suspect the problem is my incorrect usage of warp level intrinsics, which work differently from Volta onwards.
I fixed this issue in 1cff326, hopefully this takes care of the hanging problem.

**Comment by Kuranes** [comment]
Quick tested, it fixes it, no more stuck, very nice and quick find, thanks!

**Comment by Zachary-Zuo** [comment]
It has been resolved, thanks for your help.
