### ISSUE TITLE
qbvh and other bvhs

### ISSUE THREAD

**Issue by tigrazone** [jan-van-bergen/GPU-Pathtracer#23]
Is qbvh fast in traverse?
Is qbvh builder use sah and bins on building stage?
Is qbvh faster then others?
Which bvh is faster in traverse and building and quality?

**Comment by jan-van-bergen** [comment]
The QBVH (4-way tree) and CWBVH (8-way tree) are both constructed by first building a 2-way tree (using full SAH, no binning yet) and then collapsing it (also based on SAH).
The time it takes to collapse is negligable compared to the first building step.

On my laptop (with a Geforce 845m) the frame times for Sponza are as follows:
| BVH Type | Time   |
|----------|--------|
| BVH      | 416 ms |
|  QBVH    | 210 ms |
| CWBVH    | 92 ms  |

So each BVH is about twice as fast to traverse as the previous.

**Comment by tigrazone** [comment]
Is your CWBVH build code is good without enable_bvh_optimization?
or for CWBVH building enable_bvh_optimization is needed?
optimization took too much time

**Comment by jan-van-bergen** [comment]
No BVH optimization is not strictly needed for good performance, but it can be used to squeeze out the last bit of performance at the cost of more preprocessing time.
I guess I should actually disable it by default to get faster startup time.

**Comment by tigrazone** [comment]
One more question. Did CWBVH faster then sbvh in traversing?

**Comment by tigrazone** [comment]
Thank you for answers
